### ISSUE TITLE
cannot load `datetime` objects

### ISSUE THREAD

**Issue by terhorstd** [INM-6/datareport#6]
when loading a yaml file using tags like

    - !!python/object/apply:datetime.timedelta [0, 7200, 0]

the loader raises an exception:

```
INFO:root:loading 'data' from '../all.yaml'...
Traceback (most recent call last):
  File ".../bin/reporter", line 10, in <module>
    sys.exit(main())
  File ".../lib/python3.6/site-packages/datareport/reporter.py", line 139, in main
    data[dataid] = dataloader(open(datafilename, 'r'))
  File ".../lib/python3.6/site-packages/ruamel/yaml/main.py", line 266, in load
    return constructor.get_single_data()
  File ".../lib/python3.6/site-packages/ruamel/yaml/constructor.py", line 104, in get_single_data
    return self.construct_document(node)
  File ".../lib/python3.6/site-packages/ruamel/yaml/constructor.py", line 114, in construct_document
    for dummy in generator:
  File ".../lib/python3.6/site-packages/ruamel/yaml/constructor.py", line 605, in construct_yaml_seq
    data.extend(self.construct_sequence(node))
  File ".../lib/python3.6/site-packages/ruamel/yaml/constructor.py", line 196, in construct_sequence
    for child in node.value]
  File ".../lib/python3.6/site-packages/ruamel/yaml/constructor.py", line 196, in <listcomp>
    for child in node.value]
  File ".../lib/python3.6/site-packages/ruamel/yaml/constructor.py", line 159, in construct_object
    data = constructor(self, node)
  File ".../lib/python3.6/site-packages/ruamel/yaml/constructor.py", line 631, in construct_undefined
    node.start_mark)
ruamel.yaml.constructor.ConstructorError: could not determine a constructor for the tag 'tag:yaml.org,2002:python/object/apply:datetime.timedelta'
  in "../all.yaml", line 2, column 5
```

**Comment by terhorstd** [comment]
probably a confined set of constructors may be added to the SafeConstructor using a mechansim like described [here on stackoverflow](https://stackoverflow.com/questions/45966633/yaml-error-could-not-determine-a-constructor-for-the-tag#45967047)

**Comment by terhorstd** [comment]
:construction:  _WORKAROUND_  :construction: 
For now you can use `--yaml-loader=unsafe` (see also https://github.com/INM-6/datareport/issues/5)
